version: '3.8'
services:
  api:
    image: uszkers/angular-bootcamp
    ports:
      - 3000:3000
  mongodb:
    image: mongo:latest
    container_name: angularbootcamp
    ports:
      - 27017:27017
    volumes:
      - angular_bootcamp:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  angular_bootcamp:
